[build]
base = "contact-form-backend"  # Adjust this to the folder where your backend's package.json is located
command = "npm run build"
publish = "frontend/build"  # Adjust this according to your frontend build output directory
