[build]
  command = "npm run build"  # Replace with your build command if needed
  publish = "frontend"       # Replace 'frontend' with your actual frontend directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
